# Copyright 2025 Softwell S.r.l. - SPDX-License-Identifier: Apache-2.0
"""Phase 8 contract — grammar reference generated by introspection.

docs/grammar.md is committed and regenerable: generate_grammar_md() must
reproduce it byte-identically (anti-drift), and every grammar element must
appear as a section with its parameter table.
"""
from __future__ import annotations

from pathlib import Path

from genro_sql import SqlBuilder
from genro_sql.modern.grammar_doc import generate_grammar_md

REPO_ROOT = Path(__file__).resolve().parents[1]
DOC_PATH = REPO_ROOT / "docs" / "grammar.md"

ELEMENTS = (
    "db", "schema", "table",
    "column", "aliasColumn", "formulaColumn", "subQueryColumn",
    "pyColumn", "compositeColumn",
    "relation", "constraint", "index", "extension",
)


def test_doc_exists_and_is_current():
    assert DOC_PATH.exists()
    assert generate_grammar_md() == DOC_PATH.read_text(encoding="utf-8")


def test_every_element_has_a_section():
    text = DOC_PATH.read_text(encoding="utf-8")
    for tag in ELEMENTS:
        assert f"### `{tag}`" in text or f"## `{tag}`" in text, tag


def test_parameter_tables_carry_types_and_defaults():
    # wf:contract: for each element the doc lists every signature parameter
    # wf:contract: with its type and default, and marks the plane
    # wf:contract: (physical/semantic) at least for the column family.
    text = DOC_PATH.read_text(encoding="utf-8")
    assert "dtype" in text and "sql_type" in text
    assert "physical" in text.lower() and "semantic" in text.lower()


def test_doc_matches_the_grammar_not_a_copy():
    # the generator reads the live grammar: every element in the class
    # schema that is not an underscore/data element appears in the doc
    text = DOC_PATH.read_text(encoding="utf-8")
    for node in SqlBuilder._class_schema:
        label = node.label
        if label.startswith("_") or label.startswith("data"):
            continue
        assert f"`{label}`" in text, label
